import uuid
from datetime import date, time, timedelta
from django.utils import timezone
from rest_framework.test import APITestCase
from django.contrib.auth import get_user_model
from django.urls import reverse
from apps.reflections.models import Reflection
from apps.reminders.models import Reminder
from apps.sync.services import SyncService

User = get_user_model()


class SyncEngineTests(APITestCase):
    def setUp(self):
        self.user = User.objects.create_user(email="sync@example.com", password="password123")
        self.client.force_authenticate(user=self.user)
        self.sync_url = reverse("sync")
        self.service = SyncService()

    def test_sync_initial_client_records(self):
        """
        Verify that new records generated by client are inserted into DB.
        """
        ref_id = str(uuid.uuid4())
        rem_id = str(uuid.uuid4())
        
        payload = {
            "reflections": [
                {
                    "id": ref_id,
                    "date": "2026-07-16",
                    "reflection_text": "Written offline",
                    "version": 1,
                    "is_deleted": False,
                    "updated_at": timezone.now().isoformat()
                }
            ],
            "reminders": [
                {
                    "id": rem_id,
                    "time": "07:30:00",
                    "enabled": True,
                    "repeat_daily": True,
                    "version": 1,
                    "is_deleted": False,
                    "updated_at": timezone.now().isoformat()
                }
            ],
            "last_sync_time": None
        }

        response = self.client.post(self.sync_url, payload, format="json")
        self.assertEqual(response.status_code, 200)
        self.assertTrue(response.data["success"])
        self.assertIn(ref_id, response.data["synced_uuids"])
        self.assertIn(rem_id, response.data["synced_uuids"])

        # Check DB states
        self.assertTrue(Reflection.objects.filter(id=ref_id, user=self.user).exists())
        self.assertTrue(Reminder.objects.filter(id=rem_id, user=self.user).exists())

    def test_sync_conflict_resolution(self):
        """
        Verify conflict resolution:
        1. Client version is newer -> Client wins, DB updated.
        2. Server version is newer -> Server wins, client receives server update.
        """
        ref_id_client_wins = uuid.uuid4()
        ref_id_server_wins = uuid.uuid4()
        
        now = timezone.now()
        
        # 1. Create a server reflection that will be overridden by client
        ref_overridden = Reflection.objects.create(
            id=ref_id_client_wins,
            user=self.user,
            date=date(2026, 7, 15),
            reflection_text="Old server text",
            version=1,
            updated_at=now - timedelta(hours=2)
        )

        # 2. Create a server reflection that has a newer version than what client sends
        ref_newer = Reflection.objects.create(
            id=ref_id_server_wins,
            user=self.user,
            date=date(2026, 7, 16),
            reflection_text="New server text",
            version=3,
            updated_at=now
        )

        payload = {
            "reflections": [
                {
                    "id": str(ref_id_client_wins),
                    "date": "2026-07-15",
                    "reflection_text": "Updated client text",
                    "version": 2,  # Client version is 2 > Server version 1 (Client wins)
                    "is_deleted": False,
                    "updated_at": now.isoformat()
                },
                {
                    "id": str(ref_id_server_wins),
                    "date": "2026-07-16",
                    "reflection_text": "Old client text",
                    "version": 1,  # Client version is 1 < Server version 3 (Server wins)
                    "is_deleted": False,
                    "updated_at": (now - timedelta(hours=5)).isoformat()
                }
            ],
            "reminders": [],
            "last_sync_time": (now - timedelta(days=1)).isoformat()
        }

        response = self.client.post(self.sync_url, payload, format="json")
        self.assertEqual(response.status_code, 200)
        self.assertTrue(response.data["success"])
        
        # Both client UUIDs are processed and marked synced
        self.assertIn(str(ref_id_client_wins), response.data["synced_uuids"])
        self.assertIn(str(ref_id_server_wins), response.data["synced_uuids"])

        # Check DB to verify client won on the first record
        ref_overridden.refresh_from_db()
        self.assertEqual(ref_overridden.reflection_text, "Updated client text")
        self.assertEqual(ref_overridden.version, 2)

        # Verify server wins returned the server's version in the reflections response list
        server_updates = response.data["reflections"]
        self.assertEqual(len(server_updates), 1)
        self.assertEqual(server_updates[0]["id"], str(ref_id_server_wins))
        self.assertEqual(server_updates[0]["reflection_text"], "New server text")
        self.assertEqual(server_updates[0]["version"], 3)
